#!/bin/bash
# $1 = Heroku App name (ex: my_app)
# $2 = Database name (ex: my_app_development)

# Check params
if [ $# -eq 0 ]; then
  echo "Usage: pg_restore_heroku app_name local_db_name"
  exit 1
fi

set -x

TEMP_DIR="/tmp/${1}_restore"
DUMP_FNAME="${1}.dump"

# Create working directories
rm -rf $TEMP_DIR
mkdir -p $TEMP_DIR
cd $TEMP_DIR

# Download the latest backup from Heroku
heroku pg:backups:download -o $DUMP_FNAME --app $1

# Create the database
psql --host=localhost --dbname=postgres --command="DROP DATABASE IF EXISTS $2"
psql --host=localhost --dbname=postgres --command="CREATE DATABASE $2"

# Restore dump
pg_restore --clean --no-acl --no-owner --jobs=4 --host=localhost --dbname=$2 $DUMP_FNAME > pg_restore.log


set +x
cd -

# Print message
echo "Finished!"
echo "To clean temp data, run: rm ${TEMP_DIR}/${DUMP_FNAME}"
