#!/bin/bash
set -x

# The data folder should have been initialized with: `initdb -D /usr/local/pgsql/data` 
data_folder=${PG_DATA_PATH:-/Users/diego/Development/pg/data/}
log_file=${PG_LOG_FILE:-/Users/diego/Development/pg/data/logfile}
pg_ctl -D $data_folder -l $log_file stop
