#!/bin/bash
# This file contains useful command aliases
# Include the file in the `.bash_profile` file using:
#
#  if [ -f /path/to/bash_utils/aliases ]; then
#    . /path/to/bash_utils/aliases
#  fi

# General shell aliases
alias ll='ls -lah'
alias vat='vimcat'

# Rails dev aliases
alias be='bundle exec'
alias besu="NOCOV=1 SKIP_WEBPACK_COMPILE=true bundle exec rspec `git status -s | cut -c4- | grep 'spec/'`"
alias mall='bundle exec rake db:migrate db:test:prepare factory_bot:lint'
alias t='bundle exec rspec'
alias tf='bundle exec rspec --only-failures'
alias rc='bundle exec ./bin/rails console'
alias srv='bundle exec ./bin/rails server'
alias hrc='heroku run rails console' # Add --app [app_name]
alias hrun='heroku run' # Add --app [app_name]

# Git aliases
alias cb='git checkout'
alias mkb='git checkout -b'
alias rmb='git branch -d'
alias rmbf='git branch -D'

__git_complete cb _git_checkout
__git_complete mkb _git_checkout
__git_complete rmb _git_branch
__git_complete rmbf _git_branch
